//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03Model.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tStudent
    {   //表單驗證必填寫的require
        //range0~100
        //Datatype
        //compare
        //Formate格式
        //商業邏輯

        [DisplayName("學號")]
        [Required(ErrorMessage ="此為必填項目")]
        [RegularExpression("[1-3]0[0-9]{4}",ErrorMessage ="學號格式錯誤")]//另外的寫法("[123]0[0-9][0-9][0-9][0-9]{4}")] //{2,6}最少兩碼最多六碼
        public string fStuId { get; set; }

        [DisplayName("姓名")]
        [Required(ErrorMessage = "此為必填項目")]
        //[StringLength(50)] 不必限制性名
        public string fName { get; set; }

        [DisplayName("電子郵件")]
        [Required(ErrorMessage = "此為必填項目")]
        [EmailAddress(ErrorMessage = "電子郵件格式錯誤!")]
        public string fEmail { get; set; }

        [DisplayName("成績")]
        [Range(0,100,ErrorMessage ="成績請填0~100的數字!")]
        public Nullable<int> fScore { get; set; }
    }
}
