//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineToss.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Orders = new HashSet<Orders>();
        }

        [DisplayName(" 員工編號 ")]
        [Required(ErrorMessage = "此為必填項目")]
        public string EmpID { get; set; }
        
        [DisplayName(" 姓  名 ")]
        [Required(ErrorMessage = "此為必填項目")]
        public string EmpName { get; set; }
        [DisplayName("性別")]
        [Required(ErrorMessage = "此為必填項目")]
        public bool Gender { get; set; }
        [DisplayName("電話")]
        [Required(ErrorMessage = "此為必填項目")]
        public string Phone { get; set; }
        [DisplayName("地址")]
        [Required(ErrorMessage = "此為必填項目")]
        public string Address { get; set; }
        [DisplayName("生日")]
        [Required(ErrorMessage = "此為必填項目")]
        public System.DateTime Birthday { get; set; }
        [DisplayName("薪資")]
        public Nullable<decimal> Salary { get; set; }

        [DisplayName("雇用日")]
        [Required(ErrorMessage = "此為必填項目")]
        public System.DateTime Bdate { get; set; }

        [DisplayName("記事")]
        public string Notes { get; set; }

        [DisplayName("管理")]
        public string Manager { get; set; }

        [DisplayName("郵箱")]
        public string Email { get; set; }

        [DisplayName("帳號")]
        [Required(ErrorMessage = "此為必填項目")]
        public string Account { get; set; }

        [DisplayName("密碼")]
        [Required(ErrorMessage = "此為必填項目")]
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
