//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineToss.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderDetails
    {
        [Key]
        [DisplayName ("訂單編號")]
        [Required(ErrorMessage = "請填寫訂單編號")]
        public string OrderID { get; set; }

        [DisplayName("商品編號")]
        [Required(ErrorMessage = "請填寫商品編號")]
        public string ProID { get; set; }

        [DisplayName("商品售價")]
        [Required(ErrorMessage = "請填寫商品售價")]
        public decimal Price { get; set; }

        [DisplayName("商品數量")]
        [Required(ErrorMessage = "請填寫商品數量")]
        public int Qty { get; set; }

        [DisplayName("運費")]
        
        public Nullable<decimal> Fee { get; set; }

        [DisplayName("小計")]
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
