//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineToss.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Toss
    {
        [DisplayName("編  號")]
        [Required(ErrorMessage = "請填編號")]
        public string TossID { get; set; }

        [DisplayName("籤  號")]
        [Required(ErrorMessage = "請填籤號")]
        public string TossName { get; set; }
        [DisplayName("籤  詩")]
        public string Content { get; set; }
        [DisplayName("詩　意")]
        public string Poetry { get; set; }
        [DisplayName("解　曰")]
        public string Explain { get; set; }
        [DisplayName("解　說")]
        public string Description { get; set; }
        [DisplayName("圖　片")]
        public byte[] TPhoto { get; set; }

        [DisplayName("圖片路徑")]
        public string PhotoPath { get; set; }
    }
}
