//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _06ADOnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 訂單明細
    {
        public string 訂單代號 { get; set; }
        public string 產品編號 { get; set; }
        public int 購買數量 { get; set; }
    
        public virtual 訂單資料表 訂單資料表 { get; set; }
        public virtual 產品資料表 產品資料表 { get; set; }
    }
}
