//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04ViewModel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;

    public partial class tDepartment
    {
        [DisplayName("部門代碼")]
        public int fDepId { get; set; }

        [DisplayName("部門名稱")]
        [Required(ErrorMessage = "部門名稱必填")]
        public string fDepName { get; set; }
    }
}
