//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04ViewModel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tEmployee
    {
        [DisplayName("員工代碼")]
        [Required(ErrorMessage ="員工代碼是必填")]
        [RegularExpression("[A-FS-X][0-9]{2}",ErrorMessage ="格式有誤!")]
        [Key]
        public string fEmpId { get; set; }

        [DisplayName("員工姓名")]
        [Required(ErrorMessage = "員工姓名是必填")]
        public string fName { get; set; }

        [DisplayName("電話")]
        public string fPhone { get; set; }

        [DisplayName("部門代碼")]
        public Nullable<int> fDepId { get; set; }
    }
}
